-- Exercise 3

-- Get the revenue generated by each customer for the month of 2014 january.

-- - Tables - `orders`, `order_items` and `customers`
-- - Data should be sorted in descending order by revenue and then ascending order by `customer_id`
-- - Output should contain `customer_id`, `customer_fname`, `customer_lname`and `customer_revenue`.
-- - If there are no orders placed by customer, then the corresponding revenue for a given customer should be 0.
-- - Consider only `COMPLETE` and `CLOSED` orders.

SELECT customer_id,customer_fname,customer_lname, SUM(order_item_subtotal) AS customer_revenue
FROM order_items oi
LEFT JOIN orders o
ON oi.order_item_order_id=o.order_id
LEFT JOIN customers c
ON o.order_customer_id=c.customer_id
WHERE order_date BETWEEN '2014-01-01' AND '2014-01-31' AND order_status IN ('COMPLETE','CLOSED')
GROUP BY customer_id,customer_fname,customer_lname
ORDER BY customer_revenue DESC, customer_id
